# path to the file, containing all data (one document per line), which should be filtered
in_file: files/blob.txt

# text language
# supported languages:
#  - German
language: German

# number of files, the main file will be split into,
# which is used for parallel processing, 
# we suggest, to take number of cores/threats (nproc --all)
num_files: 8

# lines of the input file
# if you have a large file which number of lines are known, it saves you time to define it
# otherwise, just use some number <=0 and the workflow will count the lines for you
file_lines: 0

# output directory, relative from the workflow folder
dir_output: '../output'

# quality threashold for language detection
# the higher, the more accurate the language confimity must be
whatlang_threashold: 1.0

# minimal tokens a document should have; documents with less tokens are filtered out.
min_tokens: 40

# in order to filter meaningless spam, we compute a stopword ratio
#  len(token(document_without_stopwords))/len(token(document))
# the higher the ratio, less stopwords, which is often the case in spam lists.
# We filter out all documents with a ratio >= threshold.
threshold_stopword: 0.9

# A token ratio is computed by 
#  len(set(token(document_without_stopwords)))/len(token(document))
# which reflects the repetition of words. 
# The higher the score, the more words besides stopwords, are used,
# which usually reflects a higher variance of the document.
# We filter out all documents with a ratio <= threshold.
threshold_token: 0.4