configfile: "config.yaml"

# from iso639 import languages
import os

def output(file, output_dir = config['dir_output']):
  return os.path.join(output_dir, file)

rule all:
  input: 
    result=output('filtered.txt'),
    fail=output('fail.txt'),
    doc_count=output('count.txt')

rule compile_rust:
  output: 
    langdetect="scripts/langdetect/target/release/langdetect",
    compute_ratios="scripts/compute_ratios/target/release/compute_ratios"
  conda: "envs/rust.yaml"
  shell: r"""
    # using the conda installed linker
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-conda_cos6-linux-gnu-cc \
      cargo build --release --manifest-path scripts/langdetect/Cargo.toml
    
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-conda_cos6-linux-gnu-cc \
      cargo build --release --manifest-path scripts/compute_ratios/Cargo.toml
  """

rule compute_ratio_test:
  output: 
    result=output(config["ratio_file_test"])
  input:
    compute_ratios_bin="scripts/compute_ratios/target/release/compute_ratios",
    txt=config["svm_txt_test"],
    stopwords=config["ratio_stop_words"]
  shell: r"""
    {input.compute_ratios_bin} --stop {input.stopwords} \
      --in {input.txt} --out {output.result}
  """

rule compute_ratio_train:
  output: 
    result=output(config["ratio_file_train"])
  input:
    compute_ratios_bin="scripts/compute_ratios/target/release/compute_ratios",
    txt=config["svm_txt_train"],
    stopwords=config["ratio_stop_words"]
  shell: r"""
    {input.compute_ratios_bin} --stop {input.stopwords} \
      --in {input.txt} --out {output.result}
  """
  

rule train_svm:
  input:
    test=output(config["ratio_file_test"]),
    train=output(config["ratio_file_train"]),
    gt=config["svm_file_gt"]
  output:
    model=output(config['svm_file_model']),
    metrics=output(config['svm_file_metrics']),
    log=output(config['svm_file_train_log'])
  conda: "envs/svm.yaml"
  shell: r"""
    scripts/create_SVM_model.py \
      --gt {input.gt} \
      --test {input.test} \
      --train {input.train} \
      --out {output.model} \
      --metrics {output.metrics} \
      --log {output.log} \
      --nu {config[svm_nu]}
  """

rule split_file:
  input: config['in_file']
  output: expand(output("tmp/split_{part}.txt"), part=range(1,config['num_files']+1))
  params:
    output=output("tmp/split_")
  shell: r"""
    # get lines of file
    if [[ {config[file_lines]} -gt 0 ]]; then
      total_lines={config[file_lines]}
    else
      total_lines=$(wc -l {config[in_file]} | cut -d" " -f1)
    fi

    # compute how many files to result the split to
    ((lines_per_file = (total_lines + {config[num_files]}) / ({config[num_files]})))

    # do the split
    split \
      --numeric-suffixes=1\
      --additional-suffix=".txt" \
      --lines=$lines_per_file "{config[in_file]}" "{params.output}"

    # rename files, i.e. form split_0001000.txt to split_1000.txt
    for file in {params.output}*
    do
      new_name=$(echo $file | sed -E 's/(.+_)0*([1-9].*)/\1\2/')
      
      if [[ ! -f $new_name ]]; then
        mv $file $new_name
      fi
    done
  """

rule clean_content:
  input: output("tmp/split_{part}.txt")
  output: temp(output("tmp/clean_{part}.txt"))
  shell: r"""
    scripts/clean_it.sh {input} \
      | scripts/mosesdecoder/scripts/tokenizer/replace-unicode-punctuation.perl \
      | scripts/mosesdecoder/scripts/tokenizer/remove-non-printing-char.perl > {output}
  """

rule filter_documents:
  input: 
    bin="scripts/langdetect/target/release/langdetect",
    data=output("tmp/clean_{part}.txt")
  output: 
    success=temp(output("tmp/clean_{part}.success")),
    fail=temp(output("tmp/clean_{part}.fail")),
    doc_count=temp(output("tmp/clean_{part}.count"))
  shell: "{input.bin} -i {input.data} -s {output.success} \
    -f {output.fail} -c {output.doc_count} -l {config[language]} -t {config[whatlang_threashold]}"


rule filter_content:
  input: output("tmp/clean_{part}.success")
  output: temp(output("tmp/clean_{part}.final"))
  conda: "envs/filter.yaml"
  shell: r"""
    scripts/token_based_filter.py {input} {output} \
      {config[language]} {config[threshold_token]} \
      {config[threshold_stopword]} {config[min_tokens]}
  """


rule merge_files:
  input: 
    final=expand(output("tmp/clean_{part}.final"), part=range(1,config['num_files']+1)),
    doc_count=expand(output("tmp/clean_{part}.count"), part=range(1,config['num_files']+1)),
    fail=expand(output("tmp/clean_{part}.fail"), part=range(1,config['num_files']+1))
  output: 
    final=output("filtered.txt"),
    fail=output("fail.txt"),
    doc_count=output("count.txt")
  shell: r"""
    cat {input.final} > {output.final}
    awk '{{print $0}}' {input.doc_count} > {output.doc_count}
    cat {input.fail} > {output.fail}
  """
