configfile: "config.yaml"

from iso639 import languages
import os

def output(file, output_dir = config['dir_output']):
  return os.path.join(output_dir, file)

rule all:
  input: 
    result=output('filtered.txt'),
    fail=output('fail.txt'),
    doc_count=output('count.txt')

rule compile_rust:
  output: 
    langdetect="scripts/langdetect/target/release/langdetect"
  conda: "envs/rust.yaml"
  shell: """
    # using the conda installed linker
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-conda_cos6-linux-gnu-cc \
      cargo build --release --manifest-path scripts/langdetect/Cargo.toml
  """

rule split_file:
  input: config['in_file']
  output: expand(output("tmp/split_{part}.txt"), part=range(1,config['num_files']+1))
  params:
    n_digits=len(str(config['file_lines'])),
    output=output("tmp/split_")
  shell: """
    # get lines of file
    if [[ {config[file_lines]} -gt 0 ]]; then
      total_lines={config[file_lines]}
    else
      total_lines=$(wc -l {config[in_file]} | cut -d" " -f1)
    fi

    # compute how many files to result the split to
    ((lines_per_file = (total_lines + {config[num_files]}) / ({config[num_files]})))

    # do the split
    split \
      --numeric-suffixes=1\
      --suffix-length=1 \
      --additional-suffix=".txt" \
      --lines=$lines_per_file "{config[in_file]}" "{params.output}"
  """

rule clean_content:
  input: output("tmp/split_{part}.txt")
  output: temp(output("tmp/clean_{part}.txt"))
  shell: """
    scripts/clean_it.sh {input} \
      | scripts/mosesdecoder/scripts/tokenizer/replace-unicode-punctuation.perl \
      | scripts/mosesdecoder/scripts/tokenizer/remove-non-printing-char.perl > {output}
  """

rule filter_documents:
  input: 
    bin="scripts/langdetect/target/release/langdetect",
    data=output("tmp/clean_{part}.txt")
  output: 
    success=temp(output("tmp/clean_{part}.success")),
    fail=temp(output("tmp/clean_{part}.fail")),
    doc_count=temp(output("tmp/clean_{part}.count"))
  shell: "{input.bin} -i {input.data} -s {output.success} \
    -f {output.fail} -c {output.doc_count} -l {config[language]} -t {config[whatlang_threashold]}"


rule filter_content:
  input: output("tmp/clean_{part}.success")
  output: temp(output("tmp/clean_{part}.final"))
  conda: "envs/filter.yaml"
  shell: """
    scripts/token_based_filter.py {input} {output} \
      {config[language]} {config[threshold_token]} \
      {config[threshold_stopword]} {config[min_tokens]}
  """


rule merge_files:
  input: 
    final=expand(output("tmp/clean_{part}.final"), part=range(1,config['num_files']+1)),
    doc_count=expand(output("tmp/clean_{part}.count"), part=range(1,config['num_files']+1)),
    fail=expand(output("tmp/clean_{part}.fail"), part=range(1,config['num_files']+1))
  output: 
    final=output("filtered.txt"),
    fail=output("fail.txt"),
    doc_count=output("count.txt")
  shell: """
    (cat {input.final} > {output.final}) &
    (cat {input.doc_count} > {output.doc_count}) &
    (cat {input.fail} > {output.fail}) &
  """
