# path to the in file, containing all data (one document per line)
in_file: ../files/example/de_dedup.txt

# how many bpe tokens should be user
vocab_size: 520

# number of randomly selected documents for the validation & test set
nun_docs_valid_test_set: 120

# size in bytes, with which BPE is created e.g.: 7GB = 7000000000
size_bpe_train_file: 4000

# text language
# supported languages:
#  - German
language: German

# output directory, relative from the workflow folder
dir_output: '../output'
